<?php
/**
 * Created by PhpStorm.
 * User: sergey.gorbach
 * Date: 2015-06-23
 * Time: 15:02
 */

use Goutte\Client;

/**
 * Class locationTest
 *
 * TODO: check all forbidden urls(social counter plugin for example) + get all redirection from redirection plugin
 */
class locationTest extends AbstractMyTinySecretsBlogTest
{
	/**
	 * @beforeClass
	 */
	public static function setUpLocationsData()
	{
		$uploadsBaseDir = wp_upload_dir()['basedir'];
		foreach (array('jpeg', 'gif', 'png', 'txt') as $ext) {
			file_put_contents(sprintf('%s/wpcf7_captcha/%s.%s', $uploadsBaseDir, self::getUniqueStr(), $ext), '');
		}

		file_put_contents(sprintf('%s/profiles/%s.txt', $uploadsBaseDir, self::getUniqueStr()), '');
	}

	/**
	 * @afterClass
	 */
	public static function tearDownLocationsData()
	{
		$uploadsBaseDir = wp_upload_dir()['basedir'];
		foreach (array('jpeg', 'gif', 'png', 'txt') as $ext) {
			unlink(sprintf('%s/wpcf7_captcha/%s.%s', $uploadsBaseDir, self::getUniqueStr(), $ext));
		}
		unlink(sprintf('%s/profiles/%s.txt', $uploadsBaseDir, self::getUniqueStr()));
	}

	/**
	 * @param $url
	 * @param $status
	 * @dataProvider locationsProvider
	 */
	public function testLocation($url, $status)
	{
		$client = new Client();

		/* @var $crawler Symfony\Component\DomCrawler\Crawler */
		$crawler = $client->request('GET', $url);
		$this->assertEquals($status, $client->getResponse()->getStatus(), "Failed assert that status from url with method GET: " . $url . " = " . $status);

	}

	/**
	 * Data provider for testLocation function
	 *
	 * @return array
	 */
	public function locationsProvider()
	{
		$uploadsBaseUrl = wp_upload_dir()['baseurl'];

		return array(
			array(home_url('/xmlrpc.php'), 403),
			array(home_url('/cron/get_youtube_video.php'), 403),
			array(home_url('/phpunit/composer.json'), 403),
			array(home_url('/sitemap.xml'), 200),
			array(home_url(self::getUniqueStr()), 404),
			array(home_url('/wp-content/uploads/index.php'), 403),
			array(sprintf('%s/profiles/%s.txt', $uploadsBaseUrl, self::getUniqueStr()), 403),
			array(sprintf('%s/wpcf7_captcha/%s.txt', $uploadsBaseUrl, self::getUniqueStr()), 403),
			array(sprintf('%s/wpcf7_captcha/%s.gif', $uploadsBaseUrl, self::getUniqueStr()), 200),
			array(sprintf('%s/wpcf7_captcha/%s.jpeg', $uploadsBaseUrl, self::getUniqueStr()), 200),
			array(sprintf('%s/wpcf7_captcha/%s.png', $uploadsBaseUrl, self::getUniqueStr()), 200),
			array(home_url('/wp-content/plugins/akismet/akismet.php'), 403),
			array(home_url('/wp-content/plugins/akismet/_inc/akismet.css'), 200),
			array(home_url('/wp-content/plugins/akismet/_inc/akismet.js'), 200),
			array(home_url('/wp-content/plugins/akismet/_inc/form.js'), 200),
			array(home_url('/wp-content/plugins/akismet/_inc/img/logo-full-2x.png'), 200),
			array(home_url('/wp-content/plugins/easy-social-share-buttons/public/cache/'), 403),
			array(home_url('/wp-content/plugins/wordfence/lib/GeoIP.dat'), 403),
			array(home_url('/wp-content/plugins/wordfence/tmp/configCache.php'), 403),
			array(home_url('/wp-content/plugins/p3-profiler/classes/index.php'), 403),
			array(home_url('/wp-content/plugins/p3-profiler/exceptions/index.php'), 403),
			array(home_url('/wp-content/plugins/p3-profiler/languages/index.php'), 403),
			array(home_url('/wp-content/plugins/p3-profiler/templates/index.php'), 403),
		);
	}

	/**
	 * @param $url
	 * @param $redirectUrl
	 * @dataProvider redirectsProvider
	 */
	public function testRedirect($url, $redirectUrl)
	{
		$client = new Client();
		$client->followRedirects(false);


		/* @var $crawler Symfony\Component\DomCrawler\Crawler */
		$crawler = $client->request('GET', $url);
		$this->assertEquals($redirectUrl, $client->getResponse()->getHeader('location', true), "Redirection from url with method GET: " . $url . " to " . $redirectUrl . " failed");
	}

	/**
	 * Data provider for testRedirect function
	 * Url from apache .htaccess
	 *
	 * @return array
	 */
	public function redirectsProvider() {
		return array(
			// Custom redirect
			array( home_url( '/spread-the-love' ), 'http://www.mytinysecrets.com/sharethelove' ),
			// Forced Tier Linking Code
			array(
				home_url( '/signup-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/signup.php?ref=999999999'
			),
			// Permanent URL redirect - generated by www.rapidtables.com
			array(
				home_url( '/why-you-shouldnt-give-a-fuck-about-looks/' ),
				'http://mytinysecrets.com/why-you-should-not-give-a-fuck-about-looks/'
			),
			// TextAds
			array(
				home_url( '/999999999-azazazazazazaz-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevads.php?id=999999999&ad=999999999'
			),
			array(
				home_url( '/999999999-azazazazazazaz-999999999-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevads.php?id=999999999&ad=999999999&page=999999999'
			),
			// Standard Links
			array(
				home_url( '/999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevaffiliate.php?id=999999999'
			),
			array(
				home_url( '/999999999-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevaffiliate.php?id=999999999&page=999999999'
			),
			array(
				home_url( '/999999999-999999999-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevaffiliate.php?id=999999999&page=999999999&set=999999999'
			),
			array(
				home_url( '/999999999-999999999-999999999-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevaffiliate.php?id=999999999&page=999999999&set=999999999&link=999999999'
			),
			array(
				home_url( '/999999999-999999999-999999999-999999999-azazazazazazaz.html' ),
				'http://mytinysecrets.com/sharethelove/idevaffiliate.php?id=999999999&page=999999999&set=999999999&link=999999999&keyword=azazazazazazaz'
			),
			array(
				home_url( '/999999999-999999999-999999999-999999999-azazazazazazaz-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevaffiliate.php?id=999999999&page=999999999&set=999999999&link=999999999&keyword=azazazazazazaz&custom=999999999'
			),
			array(
				home_url( '/999999999-999999999-999999999-999999999-azazazazazazaz-999999999-999999999.html' ),
				'http://mytinysecrets.com/sharethelove/idevaffiliate.php?id=999999999&page=999999999&set=999999999&link=999999999&keyword=azazazazazazaz&custom=999999999&url=999999999'
			),
			// End iDevAffiliate SEO Code
			array(
				home_url( '/wiredtree' ),
				'http://wiredtree.com'
			),
		);
	}
}